#!/bin/bash

SSH=192.168.1.111
SSHUSER=pi

sudo sshfs $SSHUSER@$SSH:/var/www/html /mnt -o allow_other

MIRRORPATH=/mnt/mirror/snowdrop/files

function repo-up {

        mkdir -p $HOME/database/$REPO/i686
        repo-add $HOME/database/$REPO/i686/$REPO.db.tar.gz $REPOPATH/i686/*pkg.tar.xz

        mkdir -p $HOME/database/$REPO/x86_64
        repo-add $HOME/database/$REPO/x86_64/$REPO.db.tar.gz $REPOPATH/x86_64/*pkg.tar.xz
}

clear
echo Updating Stable Repository? \(y/n\)
read ANSWER

if [ $ANSWER = y ]
then
	REPO=stable
	REPOPATH=$MIRRORPATH/$REPO/os
	repo-up
fi

clear
echo Updating Core Repository? \(y/n\)
read ANSWER

if [ $ANSWER = y ]
then
        REPO=core
        REPOPATH=$MIRRORPATH/$REPO/os
        repo-up
fi

clear
echo Updating Community Repository? \(y/n\)
read ANSWER

if [ $ANSWER = y ]
then
	REPO=community
        REPOPATH=$MIRRORPATH/$REPO/os
        repo-up
fi

clear
echo Updating Extra Repository? \(y/n\)
read ANSWER

if [ $ANSWER = y ]
then
        REPO=extra
        REPOPATH=$MIRRORPATH/$REPO/os
        repo-up
fi

clear
echo Transfer Update to Server? \(y/n\)
read ANSWER

if [ $ANSWER = y ]
then
	scp -r $HOME/database $SSHUSER@$SSH:/home/pi
fi

rm -R $HOME/database
sudo fusermount -u /mnt
clear


