#!/bin/sh

check="$HOME/.config/gnome-app-folder-plus/app-folder"

if [ -f "$check" ]
then

        exit
fi

mkdir -p $HOME/.config/gnome-app-folder-plus
echo "App-Folder=true" > $check


gsettings set org.gnome.desktop.app-folders folder-children "['Installed','Multimedia','Games','Services','Office','Web','System']"


gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Installed/ name 'Installed.directory'

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Installed/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Installed/ categories "['']"

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Installed/ excluded-apps "['quodlibet.desktop','asunder.desktop','brasero.desktop','empathy.desktop','eog.desktop','evince.desktop','firefox.desktop','gimp.desktop','gnome-control-center.desktop','gnome-mines.desktop','gnome-sudoku.desktop','gnome-system-monitor.desktop','libreoffice-startcenter.desktop','org.gnome.baobab.desktop','org.gnome.Calculator.desktop','org.gnome.Calendar.desktop','org.gnome.Cheese.desktop','org.gnome.Contacts.desktop','org.gnome.DiskUtility.desktop','org.gnome.FileRoller.desktop','org.gnome.gedit.desktop','org.gnome.gnome-2048.desktop','org.gnome.Nautilus.desktop','org.gnome.Screenshot.desktop','org.gnome.Software.desktop','org.gnome.Terminal.desktop','org.gnome.Totem.desktop','org.kde.kdenlive.desktop','sol.desktop','system-config-printer.desktop','telegramdesktop.desktop','thunderbird.desktop','yelp.desktop']"


gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Multimedia/ name 'Multimedia.directory'

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Multimedia/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Multimedia/ apps "['quodlibet.desktop','org.gnome.Totem.desktop','org.kde.kdenlive.desktop','eog.desktop','gimp.desktop']"


gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ name 'Game.directory' 

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Games/ apps "['sol.desktop','gnome-mines.desktop','gnome-sudoku.desktop','org.gnome.gnome-2048.desktop']"


gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Services/ name 'Services.directory'

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Services/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Services/ apps "['org.gnome.Cheese.desktop','org.gnome.Screenshot.desktop','org.gnome.gedit.desktop','asunder.desktop','org.gnome.FileRoller.desktop','brasero.desktop']"


gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Office/ name 'Office.directory'

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Office/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Office/ apps "['org.gnome.Contacts.desktop','evince.desktop','org.gnome.Calculator.desktop','libreoffice-startcenter.desktop','org.gnome.Calendar.desktop']" 


gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Web/ name 'Web.directory'

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Web/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Web/ apps "['telegramdesktop.desktop','firefox.desktop','empathy.desktop','thunderbird.desktop']"



gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/System/ name 'System.directory'

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/System/ translate true 

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/System/ apps "['org.gnome.Nautilus.desktop','gnome-control-center.desktop','org.gnome.DiskUtility.desktop','org.gnome.baobab.desktop','yelp.desktop','gnome-system-monitor.desktop','org.gnome.Terminal.desktop','org.gnome.Software.desktop','system-config-printer.desktop']"

